version: '3.4'

services:
  node-ex-app-docker-compose:
    image: node-ex-app-docker-compose
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - 1433